
import { Navbar } from '@/components/Navbar';
import { Footer } from '@/components/Footer';

export default function LegalPage() {
    return (
        <main className="min-h-screen bg-white">
            <Navbar />

            <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
                <h1 className="font-serif text-4xl font-bold text-gray-900 mb-2">Legal Information</h1>
                <p className="text-gray-500 mb-12">Last Updated: January 5, 2026</p>

                <div className="prose prose-stone max-w-none">

                    {/* Section 1 */}
                    <section className="mb-12">
                        <h2 className="text-2xl font-bold text-gray-900 mb-4">1. Fair Use & News Aggregation Notice</h2>
                        <p className="text-gray-600 leading-relaxed mb-4">
                            FireWatch Global operates as a transformative news aggregation and intelligence portal specifically designed for the professional fire service community.
                        </p>
                        <p className="text-gray-600 leading-relaxed">
                            Our use of third-party headlines, snippets, and data falls under the principles of <strong>Fair Use (U.S.)</strong> and <strong>Fair Dealing (International)</strong> for the purposes of news reporting, criticism, research, and professional education. We provide transformative value through AI-driven summarization, categorization, and professional context analysis. We always link back to the original source and claim no ownership over third-party reporting.
                        </p>
                    </section>

                    {/* Section 2 */}
                    <section className="mb-12">
                        <h2 className="text-2xl font-bold text-gray-900 mb-4">2. Intellectual Property Rights</h2>
                        <p className="text-gray-600 leading-relaxed">
                            Content generated by FireWatch Global (including our AI summaries, layout, code, and specific "FireWatch" branding) is © 2026 FireWatch Global.
                        </p>
                        <p className="text-gray-600 leading-relaxed mt-4">
                            All third-party trademarks, logos, and news content displayed on this site remain the property of their respective owners. The use of such trademarks or content is solely for identification and descriptive purposes to facilitate news reporting.
                        </p>
                    </section>

                    {/* Section 3 */}
                    <section className="mb-12 bg-gray-50 p-6 border-l-4 border-signal-red">
                        <h2 className="text-xl font-bold text-gray-900 mb-4">3. DMCA & Takedown Policy</h2>
                        <p className="text-gray-600 leading-relaxed mb-4">
                            We respect the intellectual property rights of others. If you believe your copyrighted work has been used in a way that constitutes copyright infringement and is not covered by fair use, please notify our designated agent immediately.
                        </p>
                        <p className="text-gray-600 leading-relaxed font-bold">
                            Contact for Takedowns: <a href="mailto:legal@firewatch.global" className="text-signal-red hover:underline">legal@firewatch.global</a>
                        </p>
                        <p className="text-gray-500 text-sm mt-4">
                            Please provide: (1) Identification of the work, (2) Identification of the material to be removed, (3) Your contact info, and (4) A statement of good faith belief.
                        </p>
                    </section>

                    {/* Section 4 */}
                    <section className="mb-12">
                        <h2 className="text-2xl font-bold text-gray-900 mb-4">4. Liability Disclaimer</h2>
                        <p className="text-gray-600 leading-relaxed">
                            <strong>No Professional Advice:</strong> The information provided on this website including operational briefs, health studies ("The Health Ledger"), and safety alerts is for general informational purposes only. It is provided "as is" without warranty of any kind.
                        </p>
                        <p className="text-gray-600 leading-relaxed mt-4">
                            FireWatch Global is not a medical provider or a fire command authority. Users should verify all information with their local jurisdiction, command structure, or medical professionals before making operational or health decisions. We assume no liability for actions taken based on the information found here.
                        </p>
                    </section>
                </div>
            </div>

            <Footer />
        </main>
    );
}
